### ISSUE TITLE
Give user feedback if base64 encoded payload contains +

### ISSUE THREAD

**Issue by fdellwing** [justinsteven/advisories#2]
`keytool` does not allow the `+` char, but its a valid base64 string. You could check the base64 payload for the `+` char and if it is present abort the generation with a message that the payload needs to be modified to encode to a base64 string without that char. E.g. I just added `true && ` at the beginning of my payload and got a valid base64 string.

**Comment by justinsteven** [comment]
Excellent catch, thanks!

I've swapped out base64 for base32 which only uses alphanum and `=` - hopefully it keeps keytool happier.

If you notice an issue with the Metasploit module, please raise an issue or send a PR to metasploit-framework

Thanks again :pray:
